# #####################################################################
# Automatically generated by qmake (2.01a) Sun Jul 26 11:49:30 2009
# #####################################################################
TEMPLATE = app
QT += network
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/dizus/docs/faculdade/redes/jogo/tetris/server/. \
    .

# Input
HEADERS += jogador.h \
    ouvinte.h \
    roteador.h
SOURCES += jogador.cpp \
    main.cpp \
    ouvinte.cpp \
    roteador.cpp
FORMS += 
