######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 12 17:39:18 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .\
	/usr/lib/qt4/include/QtGui

# Input
SOURCES += main.cpp
